// Code generated by go-bindata.
// sources:
// data/dblayout/25549.xml
// DO NOT EDIT!

package dblayout

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _dataDblayout25549Xml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\xd1\xcd\x4a\xc4\x40\x0c\x07\xf0\x7b\x9f\x22\xe6\x5e\xab\xe2\x1e\x84\x99\x2e\xac\x65\x61\x0e\x7a\xd9\xe2\xbd\xbb\x13\x24\x90\x9d\x19\x66\x52\xa9\x6f\x2f\x2d\x8a\xf8\x49\x2f\x39\xfd\x42\x92\x7f\xcc\x76\x3a\x0b\xbc\x50\x2e\x1c\x83\xc5\xeb\xcb\x2b\xdc\xb6\x95\xe9\x76\x7b\x16\x2a\xf7\xc2\x14\xb4\xad\x00\x4c\x3f\x1c\x85\xe0\x71\x38\x93\xc5\x43\x22\x11\x84\xdd\xc8\xe2\x2d\xde\x6c\x36\xb7\x77\x38\x23\x00\xb3\x67\x12\xff\xce\xe6\x8a\xd0\xbf\x26\xb2\x58\x34\x73\x78\x46\x68\xfe\x70\x70\x18\x8f\x4a\x93\xae\xf1\x1d\x95\x53\xe6\xa4\x1c\xc3\x1a\xde\xc7\x28\xca\x69\x0d\x5d\x0e\x7b\xe0\x72\x72\xdd\x07\xe7\xa0\xbf\x5b\xe7\xbf\x10\x57\x5c\xf0\x34\x59\xd4\x3c\xd2\x67\xc7\x45\x5d\xff\xb7\xff\xd3\x90\x79\x0e\xb6\xfc\x18\x08\x75\xbd\xe4\xde\x2c\xc1\xb7\x95\x69\xbe\xfd\xe4\x2d\x00\x00\xff\xff\x99\xc5\x69\x9c\xba\x01\x00\x00")

func dataDblayout25549XmlBytes() ([]byte, error) {
	return bindataRead(
		_dataDblayout25549Xml,
		"data/dblayout/25549.xml",
	)
}

func dataDblayout25549Xml() (*asset, error) {
	bytes, err := dataDblayout25549XmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/dblayout/25549.xml", size: 442, mode: os.FileMode(420), modTime: time.Unix(1512505654, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"data/dblayout/25549.xml": dataDblayout25549Xml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"data": &bintree{nil, map[string]*bintree{
		"dblayout": &bintree{nil, map[string]*bintree{
			"25549.xml": &bintree{dataDblayout25549Xml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

